---
title:  xPack OpenOCD v{{ XBB_RELEASE_VERSION }} released

date: {{ RELEASE_DATE }}

authors: ilg-ul

# To be listed in the Releases page.
tags:
  - releases

# ----- Custom properties -----------------------------------------------------

upstream_version: "0.12.0"
upstream_commit: "dd175827"
upstream_release_date: "1 Apr 2024"

version: "{{ XBB_RELEASE_VERSION }}"
npm_subversion: "1"

download_url: https://github.com/xpack-dev-tools/openocd-xpack/releases/tag/v{{ XBB_RELEASE_VERSION }}/

---

TODO: select one summary

Version **{{ XBB_RELEASE_VERSION }}** is a maintenance release; it updates to
the latest upstream master.

Version **{{ XBB_RELEASE_VERSION }}** is a new release; it follows the upstream release.

<!-- truncate -->

import Image from '@theme/IdealImage';
import CodeBlock from '@theme/CodeBlock';

[The xPack OpenOCD](https://xpack.github.io/openocd/)
is a standalone cross-platform binary distribution of
[OpenOCD](https://openocd.org).

There are separate binaries for **Windows** (x64),
**macOS** (x64 and arm64)
and **GNU/Linux** (x64, arm64, arm).

:::note Raspberry Pi

The main targets for the GNU/Linux Arm
binaries are the **Raspberry Pi** class devices (armv7l and aarch64;
armv6 is not supported).

:::

## Download

The binary files are available from <a href={ frontMatter.download_url }>GitHub Releases</a>.

## Prerequisites

- x64 GNU/Linux: any system with **GLIBC 2.27** or higher
  (like Ubuntu 18 or later, Debian 10 or later, RedHat 8 later,
  Fedora 29 or later, etc)
- arm64/arm GNU/Linux: any system with **GLIBC 2.27** or higher
  (like Raspberry Pi OS, Ubuntu 18 or later, Debian 10 or later, RedHat 8 later,
  Fedora 29 or later, etc)
- x64 Windows: Windows 7 with the Universal C Runtime
  ([UCRT](https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c)),
  Windows 8, Windows 10
- x64 macOS: 10.13 or later
- arm64 macOS: 11.6 or later

## Install

The full details of installing the **xPack OpenOCD** on various platforms
are presented in the [Install Guide](/docs/install/).

## Compliance

The xPack OpenOCD generally follows the official
[OpenOCD](https://openocd.org) releases.

The current version is based on:

- OpenOCD version { frontMatter.upstream_version }, the development commit <a href={ `https://github.com/openocd-org/openocd/commit/${ frontMatter.upstream_commit }/` }>{ frontMatter.upstream_commit }</a> from { frontMatter.upstream_release_date }.

## Changes

There are no functional changes.

Compared to the upstream, the following changes were applied:

- the `src/openocd.c` file was edited to display the branding string
- the `contrib/60-openocd.rules` file was simplified to avoid protection
  related issues.

## Bug fixes

- none

## Enhancements

- none

## Known problems

- none

## Documentation

The original documentation is available online:

- https://openocd.org/doc/pdf/openocd.pdf

## Build

The binaries for all supported platforms
(Windows, macOS and GNU/Linux) were built using the
[xPack Build Box (XBB)](https://xpack.github.io/xbb/), a set
of build environments based on slightly older distributions, that should be
compatible with most recent systems.

For the prerequisites and more details on the build procedure, please see the
[Maintainer Info](/docs/maintainer-info/) page.

## CI tests

Before publishing, a set of simple tests were performed on an exhaustive
set of platforms. The results are available from:

- [GitHub Actions](https://github.com/xpack-dev-tools/openocd-xpack/actions/)
- [Travis CI](https://app.travis-ci.com/github/xpack-dev-tools/openocd-xpack/builds/)

## Tests

For more tests, install the package with xpm.

The simple test, consists in starting the binaries
only to identify the STM32F4DISCOVERY board.

<CodeBlock language="sh"> {
`~/Library/xPacks/@xpack-dev-tools/openocd/${ frontMatter.version }.${ frontMatter.npm_subversion }/.content/bin/openocd -f board/stm32f4discovery.cfg`
} </CodeBlock>

A more complex test consist in programming and debugging a simple blinky
application on the STM32F4DISCOVERY board. The binaries were
those generated by
[simple Eclipse projects](https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/tree/xpack/tests/eclipse)
available in the **xPack GNU Arm Embedded GCC** project.

## Checksums

The SHA-256 hashes for the files are:
