# -----------------------------------------------------------------------------
#
# This file is part of the xPack project (http://xpack.github.io).
# Copyright (c) 2025-2026 Liviu Ionescu. All rights reserved.
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose is hereby granted, under the terms of the MIT license.
#
# If a copy of the license was not distributed with this file, it can
# be obtained from https://opensource.org/licenses/mit.
#
# -----------------------------------------------------------------------------

# https://github.com/xpack-dev-tools/openocd-xpack/actions/workflows/test-sourceforge-downloads.yml
name: 'Test SourceForge downloads'

on:
  schedule:
    - cron: '24 0 * * 6' # every Saturday
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: xpack-dev-tools/xbb-helper-xpack
          ref: 'xpack-development'

      - name: Show environment
        run: |
          ls -lLA
          env | sort | grep -E '^[^ \t]+='

      - name: Run test
        run: |
          #!/usr/bin/env bash
          set -e

          # The script is in the xbb-helper-xpack repo.
          source maintenance-scripts/download-sourceforge-source.sh

          date

          # https://github.com/xpack-dev-tools/openocd-xpack/tags
          # https://sourceforge.net/projects/openocd-xpack/files/
          name="openocd"

          if [ "${GITHUB_REF_NAME}" == "xpack-development" ]
          then
            threshold=100
          else
            threshold=66
          fi

          # 2025
          platforms="win32-x64,linux-x64,linux-arm64,darwin-x64,darwin-arm64"

          download_sourceforge "${name}" "0.12.0-7" ${threshold} "${platforms}"

          # 2024-2022
          platforms="win32-x64,linux-x64,linux-arm64,linux-arm,darwin-x64,darwin-arm64"

          download_sourceforge "${name}" "0.12.0-6" ${threshold} "${platforms}"
          download_sourceforge "${name}" "0.12.0-5" ${threshold} "${platforms}"
          download_sourceforge "${name}" "0.12.0-4" ${threshold} "${platforms}"
          download_sourceforge "${name}" "0.12.0-3" ${threshold} "${platforms}"
          download_sourceforge "${name}" "0.12.0-2" ${threshold} "${platforms}"
          download_sourceforge "${name}" "0.12.0-1" ${threshold} "${platforms}"
          download_sourceforge "${name}" "0.11.0-5" ${threshold} "${platforms}"
          download_sourceforge "${name}" "0.11.0-4" ${threshold} "${platforms}"

          # 2021
          platforms="win32-x64,win32-ia32,linux-x64,linux-ia32,linux-arm64,linux-arm,darwin-x64"

          download_sourceforge "${name}" "0.11.0-3" ${threshold} "${platforms}"
          download_sourceforge "${name}" "0.11.0-2" ${threshold} "${platforms}"
          download_sourceforge "${name}" "0.11.0-1" ${threshold} "${platforms}"

          # 2019
          platforms="win32-x64,win32-x32,linux-x64,linux-x32,darwin-x64"

          download_sourceforge "${name}" "0.10.0-15" ${threshold} "${platforms}"
          download_sourceforge "${name}" "0.10.0-14" ${threshold} "${platforms}"
